name: My First Workflow

on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Github hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Print Hello World
      run: echo "Hello, World!"
    
    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node_version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Display variables
      run: | 
           echo Var GitHub Actor is: $GITHUB_ACTOR
           echo Var GitHub User is: $GITHUB_USER
           echo Var GitHub Workflow is: $GITHUB_WORKFLOW      
