name: My First Workflow

on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Github hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Print Hello World
      run: echo "Hello, World!"
